feat: 策略配置优化 --story=118179847
TencentBlueKing/bk-audit pull request #404
Opened 2024-08-02 03:04 UTC by 0RAJA

1. 创建策略接口增加风险等级，风险危害，风险指引，处理人参数
2. 策略接口支持风险标题渲染
3. 增加事件信息字段获取接口
4. 风险处理支持从策略配置获取处理人

2024-08-02 03:04 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-audit?pullRequest=404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-audit?pullRequest=404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-audit?pullRequest=404) it.</sub>

2024-08-05 07:19 UTC, OrenZhang requested changes

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +        user_info = RetrieveUser().perform_request(validated_request_data)
api.user_manage.retrieve_user

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +    platform_authorization = True
使用 PlatformAuth 后，会影响原来接口的用户认证

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +    platform_authorization = True
这个接口非标准蓝鲸API，平台认证无意义

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +    """获取单个用户的leader信息 ."""
写name可以不写doc

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +        leader_infos = user_info.get("leader", [])
这一串逻辑是否可以用try catch来实现，没有获取到leader是否直接报错而非返回空，更符合API异常的处理方式

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/core/render.py
> +logger = logging.getLogger(__name__)
使用blueapps logger

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/risk.py
> +        生成风险标题
这里可以再考虑下，生成字段列表和使用字段应该是两个配套的方法

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/ticket.py
> +        strategy: Strategy = Strategy.objects.filter(strategy_id=self.risk.strategy_id).first()
策略在初始化时获取

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/ticket.py
> +        获取处理人
获取处理人是否应该包含获取安全接口人的兜底逻辑

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/ticket.py
> +        processor_groups: List[NoticeGroup] = list(
处理组转人的逻辑是否可以放在通知组去做，以兼容后续的变化

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/ticket.py
> +        processor_groups: List[NoticeGroup] = list(
可以全局搜索下 `.group_member` 方法，一起修改

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/models.py
> +    title = models.TextField(gettext_lazy("Risk Title"), null=True, blank=True, default=None)
风险等级是否要存储在风险中

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/risk/resources/risk.py
> +        # 补充风险策略中的事件字段配置
一个接口做一件事，这些字段应该放在策略详情中

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/models.py
> +    risk_title = models.TextField(gettext_lazy("Risk Title"), null=True, blank=True, default=None)
title 不做长度控制吗

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/models.py
> +    processor_groups = models.JSONField(gettext_lazy("Processor"), default=dict, null=True, blank=True)
`default=dict` 是否符合预期

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/models.py
> +    event_basic_field_configs = models.JSONField(
都是field config 为什么要拆三个字段

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/resources.py
> +            for field in EventMappingFields().fields
event_data 和 event_evidence 是否需要排除

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/resources.py
> +        if not ActionPermission(actions=[ActionEnum.EDIT_STRATEGY]).has_permission(
权限控制放在View去做

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/serializers.py
> +            "risk_level",
这里如果不覆盖 risk_level 的 Serializer配置，会导致 risk_level 为非必填

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/serializers.py
> +            "risk_level",
根据需求描述 risk_level 不允许修改

2024-08-05 07:19 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/views.py
> +        ResourceRoute("GET", resource.strategy_v2.get_event_info_fields, endpoint="event"),
endpoint="fields_config"

2024-08-05 08:15 UTC, 0RAJA commented on src/backend/api/user_manage/default.py
> +        leader_infos = user_info.get("leader", [])
这里是为了避免业务中每次都需要 try catch，考虑提供一个统一的获取方式，修改为函数更好一些？

2024-08-05 08:52 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +        leader_infos = user_info.get("leader", [])
那就不要放在API里面

2024-08-05 11:18 UTC, 0RAJA commented on src/backend/services/web/strategy_v2/resources.py
> +            for field in EventMappingFields().fields
需要排除

2024-08-07 02:14 UTC, closed without merging