Feat strategy new
TencentBlueKing/bk-audit pull request #406
Opened 2024-08-07 03:48 UTC by 0RAJA

feat: 策略配置优化 --story=118179847

1. 创建策略接口增加风险等级，风险危害，风险指引，处理人参数
2. 策略接口支持风险标题渲染
3. 增加事件信息字段获取接口
4. 风险处理支持从策略配置获取处理人

2024-08-07 08:49 UTC, OrenZhang requested changes

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/api/user_manage/default.py
> +    cache_type = CacheTypeItem(key="RetrieveUser", timeout=TimeEnum.ONE_HOUR_SECOND.value, user_related=False)
API 不做缓存，放在业务Resource做

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/apps/notice/models.py
> +    def parse_members(cls, processor_groups: List["NoticeGroup"]) -> List[str]:
对象方法合适一些，然后在外面 [for xxx]

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/core/utils/user_manage.py
> +def retrieve_leader(validated_request_data: dict) -> Optional[str]:
可以写个Resource去做

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/risk/constants.py
> +EVENT_BASIC_FIELDS = [
使用上面的常量循环，并配置排除

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/risk.py
> +            risk_content["event_evidence"] = json.loads(risk_content["event_evidence"])[0]
需要捕获异常，如果 risk_content 不是一个json

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/risk/handlers/ticket.py
> +        strategy: Strategy = Strategy.objects.filter(strategy_id=self.risk.strategy_id).first()
不用 self 里面的吗

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/constants.py
> +
这里为什么多了一个空行

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/models.py
> +    processor_groups = models.JSONField(gettext_lazy("Processor"), default=list, null=True, blank=True)
挪到 notice_group 附近

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/models.py
> +        gettext_lazy("Event field Configs"), default=list, null=True, blank=True
"Event field Configs" -> "Event Field Configs"

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/resources.py
> +    def get_event_basic_field_configs(cls) -> List[EventInfoField]:
是不是可以用单行表达式完成，下面两个一起看下

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/serializers.py
> +            "risk_level",
risk_level 不可编辑

2024-08-07 08:49 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/views.py
> +            return [IAMPermission(actions=[ActionEnum.CREATE_STRATEGY])]
UPDATE 和 Retrieve 是否也能使用该接口

2024-08-08 01:46 UTC, OrenZhang requested changes

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/apps/notice/models.py
> +    def parse_members(cls, processor_groups: Union[QuerySet["NoticeGroup"], List["NoticeGroup"]]) -> List[str]:
processor_groups 对于 group 来说是个什么概念

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/apps/notice/models.py
> +        members = set()
单行表达式即可完成

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/apps/user_manage/resources.py
> +    name = gettext_lazy("获取单个用户的leader信息")
不缓存了吗

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/apps/user_manage/resources.py
> +        leader_infos = user_info.get("leader", [])
直接 try catch 会不会快捷一些

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/core/utils/user_manage.py
> +def retrieve_leader(validated_request_data: dict) -> Optional[str]:
这个文件留着的作用是？

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/services/web/analyze/tasks.py
> +    receivers = [{"receiver_type": "user", "username": member} for member in NoticeGroup.parse_members(notice_groups)]
为什么不直接在parse方法中parse为接受人

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/services/web/risk/constants.py
> +        example = ""
写死在这里不合理

2024-08-08 01:46 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/serializers.py
> +    processor_groups = serializers.ListField(
是否要配置个min_length

2024-08-08 12:55 UTC, OrenZhang requested changes

2024-08-08 12:55 UTC, OrenZhang commented on src/backend/apps/user_manage/resources.py
> +        user_info = api.user_manage.retrieve_user(validated_request_data)
api 也可能报错，是否一起 catch

2024-08-08 12:55 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/resources.py
> +    risk: Optional[Risk] = None
Resource 不建议存储内容在 self 里

2024-08-08 12:55 UTC, OrenZhang commented on src/backend/services/web/strategy_v2/resources.py
> +            and TicketPermission.objects.filter(
使用view相同的权限class来处理，保证一致性

2024-08-08 14:19 UTC, 0RAJA commented on src/backend/services/web/strategy_v2/resources.py
> +            and TicketPermission.objects.filter(
这里的鉴权是业务逻辑的一部分，放到 view 里感觉不太合适

2024-08-09 07:37 UTC, OrenZhang approved these changes

2024-08-09 07:48 UTC, merged